/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fxmodadd.view;

import fxmodadd.model.util.Constant;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Vìctor
 */
public class App extends javax.swing.JFrame {

    private double offsetX;
    private double offsetY;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        this.setLocationRelativeTo(null);
        visibility(true,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        panelRound3 = new Clases.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        panelRound6 = new Clases.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelRound2 = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        PanelAuto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelRound9 = new Clases.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelManual = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonWeb = new javax.swing.JRadioButton();
        jRadioButtonControls = new javax.swing.JRadioButton();
        jRadioButtonBase1 = new javax.swing.JRadioButton();
        jRadioButtonFXML = new javax.swing.JRadioButton();
        jRadioButtonGraphics = new javax.swing.JRadioButton();
        jRadioButtonMedia1 = new javax.swing.JRadioButton();
        jRadioButtonSwing1 = new javax.swing.JRadioButton();
        panelRound10 = new Clases.PanelRound();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 26, 26));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(55, 55, 55));

        panelRound3.setBackground(new java.awt.Color(21, 215, 200));
        panelRound3.setRoundBottomLeft(5);
        panelRound3.setRoundBottomRight(5);
        panelRound3.setRoundTopLeft(5);
        panelRound3.setRoundTopRight(5);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound3MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Auto");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelRound6.setBackground(new java.awt.Color(21, 215, 200));
        panelRound6.setRoundBottomLeft(5);
        panelRound6.setRoundBottomRight(5);
        panelRound6.setRoundTopLeft(5);
        panelRound6.setRoundTopRight(5);
        panelRound6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound6MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manual");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(285, 285, 285))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 285));

        panelRound2.setBackground(new java.awt.Color(80, 80, 80));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound2MouseExited(evt);
            }
        });
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("FXModAdd-v1.0");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 23));

        PanelAuto.setBackground(new java.awt.Color(26, 26, 26));
        PanelAuto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("necesary modules.");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PanelAuto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("The application will automatically ");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PanelAuto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("search for the file you want to run ");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PanelAuto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        panelRound9.setBackground(new java.awt.Color(21, 215, 200));
        panelRound9.setRoundBottomLeft(5);
        panelRound9.setRoundBottomRight(5);
        panelRound9.setRoundTopLeft(5);
        panelRound9.setRoundTopRight(5);
        panelRound9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound9MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Run App");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setMaximumSize(new java.awt.Dimension(57, 18));
        jLabel10.setMinimumSize(new java.awt.Dimension(57, 18));
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelAuto.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("within the folder it is in and add any ");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PanelAuto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jPanel1.add(PanelAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 45, 370, 240));

        PanelManual.setBackground(new java.awt.Color(26, 26, 26));
        PanelManual.setPreferredSize(new java.awt.Dimension(356, 220));
        PanelManual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(26, 26, 26));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelManual.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Give the file name:");
        PanelManual.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Select the modules to add:");
        PanelManual.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jRadioButtonWeb.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonWeb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonWeb.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonWeb.setText("javafx.web");
        jRadioButtonWeb.setFocusPainted(false);
        jRadioButtonWeb.setFocusable(false);
        jRadioButtonWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWebActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 20));

        jRadioButtonControls.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonControls.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonControls.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonControls.setText("javafx.controls");
        jRadioButtonControls.setFocusPainted(false);
        jRadioButtonControls.setFocusable(false);
        jRadioButtonControls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonControlsActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 20));

        jRadioButtonBase1.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonBase1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonBase1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonBase1.setText("javafx.base");
        jRadioButtonBase1.setFocusPainted(false);
        jRadioButtonBase1.setFocusable(false);
        jRadioButtonBase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBase1ActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 20));

        jRadioButtonFXML.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonFXML.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonFXML.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonFXML.setText("javafx.fxml");
        jRadioButtonFXML.setFocusPainted(false);
        jRadioButtonFXML.setFocusable(false);
        jRadioButtonFXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFXMLActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonFXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 20));

        jRadioButtonGraphics.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonGraphics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonGraphics.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonGraphics.setText("javafx.graphics");
        jRadioButtonGraphics.setFocusPainted(false);
        jRadioButtonGraphics.setFocusable(false);
        jRadioButtonGraphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGraphicsActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonGraphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 20));

        jRadioButtonMedia1.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonMedia1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonMedia1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonMedia1.setText("javafx.media");
        jRadioButtonMedia1.setFocusPainted(false);
        jRadioButtonMedia1.setFocusable(false);
        jRadioButtonMedia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedia1ActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonMedia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 20));

        jRadioButtonSwing1.setBackground(new java.awt.Color(26, 26, 26));
        jRadioButtonSwing1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonSwing1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonSwing1.setText("javafx.swing");
        jRadioButtonSwing1.setFocusPainted(false);
        jRadioButtonSwing1.setFocusable(false);
        jRadioButtonSwing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSwing1ActionPerformed(evt);
            }
        });
        PanelManual.add(jRadioButtonSwing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 20));

        panelRound10.setBackground(new java.awt.Color(21, 215, 200));
        panelRound10.setRoundBottomLeft(5);
        panelRound10.setRoundBottomRight(5);
        panelRound10.setRoundTopLeft(5);
        panelRound10.setRoundTopRight(5);
        panelRound10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound10MouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Run App");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setMaximumSize(new java.awt.Dimension(57, 18));
        jLabel13.setMinimumSize(new java.awt.Dimension(57, 18));
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelManual.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 30));

        jPanel1.add(PanelManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 45, 360, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_panelRound2MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        offsetX = evt.getX();
        offsetY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation((int) evt.getXOnScreen() - (int) offsetX, (int) evt.getYOnScreen() - (int) offsetY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void panelRound2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseEntered
        panelRound2.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_panelRound2MouseEntered

    private void panelRound2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseExited
        panelRound2.setBackground(new Color(80, 80, 80));
    }//GEN-LAST:event_panelRound2MouseExited

    private void panelRound9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound9MouseEntered
        panelRound9.setBackground(new Color(19, 143, 133));
    }//GEN-LAST:event_panelRound9MouseEntered

    private void panelRound9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound9MouseExited
        panelRound9.setBackground(new Color(21, 215, 200));
    }//GEN-LAST:event_panelRound9MouseExited

    private void panelRound9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound9MouseClicked
        if (Constant.autoRun())
            this.dispose();
    }//GEN-LAST:event_panelRound9MouseClicked

    private void panelRound10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound10MouseExited
        panelRound10.setBackground(new Color(21, 215, 200));
    }//GEN-LAST:event_panelRound10MouseExited

    private void panelRound10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound10MouseEntered
        panelRound10.setBackground(new Color(19, 143, 133));
    }//GEN-LAST:event_panelRound10MouseEntered

    private void panelRound10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound10MouseClicked
        String aux = "";
        ArrayList<JRadioButton> auxRadBut = new ArrayList<>();
        auxRadBut.add(this.jRadioButtonBase1);
        auxRadBut.add(this.jRadioButtonControls);
        auxRadBut.add(this.jRadioButtonFXML);
        auxRadBut.add(this.jRadioButtonGraphics);
        auxRadBut.add(this.jRadioButtonMedia1);
        auxRadBut.add(this.jRadioButtonSwing1);
        auxRadBut.add(this.jRadioButtonWeb);
        for (int i = 0; i < auxRadBut.size(); i++) {
            if (auxRadBut.get(i).isSelected()) {
                if (!aux.isEmpty()&& i < auxRadBut.size() - 1) {
                    aux += "," + auxRadBut.get(i).getText();
                } else {
                    aux += auxRadBut.get(i).getText();
                }
            }
        }
        if (Constant.autoRun(this.jTextField1.getText(), aux)){
            this.dispose();
        }
    }//GEN-LAST:event_panelRound10MouseClicked

    private void jRadioButtonSwing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSwing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSwing1ActionPerformed

    private void jRadioButtonMedia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMedia1ActionPerformed

    private void jRadioButtonGraphicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGraphicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGraphicsActionPerformed

    private void jRadioButtonFXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFXMLActionPerformed

    private void jRadioButtonBase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBase1ActionPerformed

    private void jRadioButtonControlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonControlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonControlsActionPerformed

    private void jRadioButtonWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonWebActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void panelRound6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound6MouseExited
        panelRound6.setBackground(new Color(21, 215, 200));
    }//GEN-LAST:event_panelRound6MouseExited

    private void panelRound6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound6MouseEntered
        panelRound6.setBackground(new Color(19, 143, 133));
    }//GEN-LAST:event_panelRound6MouseEntered

    private void panelRound6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound6MouseClicked
        visibility(false, true);
    }//GEN-LAST:event_panelRound6MouseClicked

    private void panelRound3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseExited
        panelRound3.setBackground(new Color(21, 215, 200));
    }//GEN-LAST:event_panelRound3MouseExited

    private void panelRound3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseEntered
        panelRound3.setBackground(new Color(19, 143, 133));
    }//GEN-LAST:event_panelRound3MouseEntered

    private void panelRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseClicked
        visibility(true, false);
    }//GEN-LAST:event_panelRound3MouseClicked
    private void visibility(boolean auto, boolean manual) {
        this.PanelAuto.setVisible(auto);
        this.PanelManual.setVisible(manual);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAuto;
    private javax.swing.JPanel PanelManual;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonBase1;
    private javax.swing.JRadioButton jRadioButtonControls;
    private javax.swing.JRadioButton jRadioButtonFXML;
    private javax.swing.JRadioButton jRadioButtonGraphics;
    private javax.swing.JRadioButton jRadioButtonMedia1;
    private javax.swing.JRadioButton jRadioButtonSwing1;
    private javax.swing.JRadioButton jRadioButtonWeb;
    private javax.swing.JTextField jTextField1;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound10;
    private Clases.PanelRound panelRound2;
    private Clases.PanelRound panelRound3;
    private Clases.PanelRound panelRound6;
    private Clases.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
}
